import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Plus, Power } from "lucide-react";
import { Card } from "@/components/ui/card";
import { useEffect,useState } from "react";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/cargos")({component:Positions});
function Positions(){const [rows,setRows]=useState<any[]>([]);const [name,setName]=useState("");const [open,setOpen]=useState(false);const [error,setError]=useState("");
async function load(){const {data,error}=await (supabase as any).from("positions").select("id,name,active").order("name");if(error)setError(error.message);else setRows(data??[])}useEffect(()=>{void load()},[]);
async function save(){if(!name.trim())return;const {error}=await (supabase as any).from("positions").upsert({name:name.trim(),active:true},{onConflict:"name"});if(error)setError(error.message);else{setName("");setOpen(false);await load()}}async function toggle(r:any){const {error}=await (supabase as any).from("positions").update({active:!r.active}).eq("id",r.id);if(error)setError(error.message);else await load()}
return <div className="min-h-screen bg-background"><header className="border-b px-6 py-4"><div className="mx-auto max-w-[1500px] flex justify-between"><Link to="/" className="text-sm text-muted-foreground">← Voltar</Link><b>DP Success · Cadastros</b></div></header><main className="mx-auto max-w-[1500px] px-6 py-7"><div className="flex justify-between items-end"><div><p className="text-sm font-medium text-primary">Cadastro base</p><h1 className="text-3xl font-bold">Cargos</h1><p className="mt-1 text-sm text-muted-foreground">Cadastre os cargos utilizados pelos funcionários.</p></div><button onClick={()=>setOpen(true)} className="rounded-lg bg-primary px-4 py-2.5 text-sm text-primary-foreground"><Plus className="inline h-4 w-4 mr-2"/>Novo cargo</button></div>{error&&<p className="mt-4 text-sm text-destructive">{error}</p>}<Card className="mt-6 overflow-hidden"><table className="w-full text-left text-sm"><thead className="bg-muted/40 text-xs text-muted-foreground"><tr><th className="px-5 py-3">Cargo</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Ação</th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="px-5 py-4 font-medium">{r.name}</td><td className="px-5 py-4">{r.active?"Ativo":"Inativo"}</td><td className="px-5 py-4"><button onClick={()=>void toggle(r)} className="text-primary"><Power className="inline h-4 w-4 mr-1"/>{r.active?"Inativar":"Ativar"}</button></td></tr>)}</tbody></table></Card></main>{open&&<div className="fixed inset-0 bg-black/40 flex items-center justify-center p-4"><Card className="w-full max-w-md p-6"><h2 className="font-bold text-lg">Novo cargo</h2><input autoFocus value={name} onChange={e=>setName(e.target.value)} className="mt-4 w-full rounded-lg border px-3 py-2" placeholder="Nome do cargo"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="rounded-lg border px-4 py-2">Cancelar</button><button onClick={()=>void save()} className="rounded-lg bg-primary px-4 py-2 text-primary-foreground">Salvar</button></div></Card></div>}</div>}