import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Plus, Power } from "lucide-react";
import { Card } from "@/components/ui/card";
import { useEffect,useState } from "react";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/jornadas-escalas")({component:Schedules});
function Schedules(){const [rows,setRows]=useState<any[]>([]);const [form,setForm]=useState({name:"",weekly:"44",divisor:"220"});const [open,setOpen]=useState(false);const [error,setError]=useState("");
async function load(){const {data,error}=await (supabase as any).from("work_schedules").select("id,name,weekly_minutes,divisor,active").order("name");if(error)setError(error.message);else setRows(data??[])}useEffect(()=>{void load()},[]);
async function save(){const weekly=Number(form.weekly)*60;const divisor=Number(form.divisor);if(!form.name||!weekly||!divisor)return;const {error}=await (supabase as any).from("work_schedules").insert({name:form.name,weekly_minutes:weekly,divisor,active:true});if(error)setError(error.message);else{setForm({name:"",weekly:"44",divisor:"220"});setOpen(false);await load()}}async function toggle(r:any){const {error}=await (supabase as any).from("work_schedules").update({active:!r.active}).eq("id",r.id);if(error)setError(error.message);else await load()}
return <div className="min-h-screen bg-background"><header className="border-b px-6 py-4"><div className="mx-auto max-w-[1500px] flex justify-between"><Link to="/" className="text-sm text-muted-foreground">← Voltar</Link><b>DP Success · Cadastros</b></div></header><main className="mx-auto max-w-[1500px] px-6 py-7"><div className="flex justify-between items-end"><div><p className="text-sm font-medium text-primary">Cadastro base</p><h1 className="text-3xl font-bold">Jornadas / Escalas</h1><p className="mt-1 text-sm text-muted-foreground">Cadastre jornadas, carga semanal e divisor.</p></div><button onClick={()=>setOpen(true)} className="rounded-lg bg-primary px-4 py-2.5 text-sm text-primary-foreground"><Plus className="inline h-4 w-4 mr-2"/>Nova jornada</button></div>{error&&<p className="mt-4 text-sm text-destructive">{error}</p>}<Card className="mt-6 overflow-hidden"><table className="w-full text-left text-sm"><thead className="bg-muted/40 text-xs text-muted-foreground"><tr><th className="px-5 py-3">Jornada</th><th className="px-5 py-3">Carga semanal</th><th className="px-5 py-3">Divisor</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Ação</th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="px-5 py-4 font-medium">{r.name}</td><td className="px-5 py-4">{Math.floor((r.weekly_minutes||0)/60)}h</td><td className="px-5 py-4">{r.divisor}h</td><td className="px-5 py-4">{r.active===false?"Inativa":"Ativa"}</td><td className="px-5 py-4"><button onClick={()=>void toggle(r)} className="text-primary"><Power className="inline h-4 w-4 mr-1"/>Alterar</button></td></tr>)}</tbody></table></Card></main>{open&&<div className="fixed inset-0 bg-black/40 flex items-center justify-center p-4"><Card className="w-full max-w-md p-6"><h2 className="font-bold text-lg">Nova jornada</h2><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-4 w-full rounded-lg border px-3 py-2" placeholder="Ex.: Administrativo 44h"/><input value={form.weekly} onChange={e=>setForm({...form,weekly:e.target.value})} type="number" className="mt-2 w-full rounded-lg border px-3 py-2" placeholder="Horas semanais"/><input value={form.divisor} onChange={e=>setForm({...form,divisor:e.target.value})} type="number" className="mt-2 w-full rounded-lg border px-3 py-2" placeholder="Divisor"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="rounded-lg border px-4 py-2">Cancelar</button><button onClick={()=>void save()} className="rounded-lg bg-primary px-4 py-2 text-primary-foreground">Salvar</button></div></Card></div>}</div>}