import{createFileRoute,Link}from"@tanstack/react-router";import{ArrowLeft,Download,FileBarChart}from"lucide-react";import{Card}from"@/components/ui/card";import{useEffect,useState}from"react";import{supabase}from"@/integrations/supabase/client";
export const Route=createFileRoute("/relatorios")({component:Relatorios});
const reports=[["fechamento","Fechamento de ponto"],["banco","Banco de horas"],["extras","Horas extras por funcionário"],["absenteismo","Absenteísmo por departamento"],["atestados","Atestados e afastamentos"],["ocorrencias","Faltas e ocorrências"]] as const;
function csv(rows:any[]){if(!rows.length)return "";const keys=Object.keys(rows[0]);const esc=(v:any)=>'"'+String(v??"").replaceAll('"','""')+'"';return [keys.join(";"),...rows.map(r=>keys.map(k=>esc(r[k])).join(";"))].join("\n")}
function download(name:string,rows:any[]){const blob=new Blob(["\ufeff"+csv(rows)],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function Relatorios(){
 const[competence,setCompetence]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{const{data,error}=await(supabase as any).from("competencies").select("id,name,start_date,end_date,status").order("end_date",{ascending:false}).limit(1);if(error)setError(error.message);setCompetence(data?.[0]??null);setLoading(false)})()},[]);
 async function exportReport(kind:string){
  setBusy(kind);setError("");const db=supabase as any;let rows:any[]=[];
  try{
   if(kind==="fechamento"){const{data,error}=await db.from("competencies").select("name,start_date,end_date,status,closed_at").order("start_date",{ascending:false}).limit(24);if(error)throw error;rows=data??[]}
   if(kind==="banco"){const{data,error}=await db.from("competence_employee_balances").select("competence_id,employee_id,opening_minutes,credit_minutes,debit_minutes,closing_minutes,estimated_value");if(error)throw error;rows=data??[]}
   if(kind==="extras"){const{data,error}=await db.from("point_launches").select("launch_date,type,minutes,rate_factor,salary_snapshot,divisor_snapshot,hour_value_snapshot,financial_value,description,employees(full_name)").order("launch_date",{ascending:false});if(error)throw error;rows=(data??[]).map((x:any)=>({date:x.launch_date,type:x.type,minutes:x.minutes,rate_factor:x.rate_factor,salary:x.salary_snapshot,divisor:x.divisor_snapshot,hour_value:x.hour_value_snapshot,financial_value:x.financial_value,description:x.description??"",employee:x.employees?.full_name??""}))}
   if(kind==="absenteismo"){const{data,error}=await db.from("occurrences").select("occurrence_date,type,minutes,description,employees(full_name,departments(name))").eq("type","Falta");if(error)throw error;rows=(data??[]).map((x:any)=>({date:x.occurrence_date,type:x.type,minutes:x.minutes,employee:x.employees?.full_name??"",department:x.employees?.departments?.name??"",description:x.description??""}))}
   if(kind==="atestados"){const{data,error}=await db.from("medical_certificates").select("start_date,end_date,days,hours,cid,notes,employees(full_name)");if(error)throw error;rows=(data??[]).map((x:any)=>({employee:x.employees?.full_name??"",start_date:x.start_date,end_date:x.end_date,days:x.days,hours:x.hours,cid:x.cid,notes:x.notes}))}
   if(kind==="ocorrencias"){const{data,error}=await db.from("occurrences").select("occurrence_date,type,minutes,description,employees(full_name)");if(error)throw error;rows=(data??[]).map((x:any)=>({date:x.occurrence_date,type:x.type,minutes:x.minutes,employee:x.employees?.full_name??"",description:x.description??""}))}
   download("dp-success-"+kind+".csv",rows)
  }catch(e:any){setError(e.message??"Não foi possível gerar o relatório.")}finally{setBusy("")}
 }
 return <div className="min-h-screen bg-background"><header className="border-b px-6 py-4"><div className="mx-auto flex max-w-[1500px] items-center justify-between"><Link to="/" className="flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Voltar</Link><span className="font-semibold">DP Success · Relatórios</span></div></header><main className="mx-auto max-w-[1500px] px-6 py-7"><p className="text-sm font-medium text-primary">Gestão</p><h1 className="mt-1 text-3xl font-bold">Relatórios</h1><p className="mt-1 text-sm text-muted-foreground">{loading?"Carregando…":competence?"Competência atual: "+competence.name:"Nenhuma competência cadastrada."}</p>{error&&<div className="mt-4 rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}<div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{reports.map(([key,title])=><Card key={key} className="p-5"><FileBarChart className="h-5 w-5 text-primary"/><h2 className="mt-4 font-bold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">Consulta os dados gravados no banco e gera arquivo CSV.</p><button onClick={()=>void exportReport(key)} disabled={!!busy} className="mt-4 inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm disabled:opacity-50"><Download className="h-4 w-4"/>{busy===key?"Gerando…":"Exportar CSV"}</button></Card>)}</div></main></div>;
}