import { Link}from"@tanstack/react-router";import{ArrowLeft,Download,FileBarChart}from"lucide-react";import{Card}from"@/components/ui/card";import{useEffect,useState}from"react";import{supabase}from"@/integrations/supabase/client";
const reports=[["fechamento","Fechamento de ponto"],["banco","Banco de horas"],["extras","Horas extras por funcionário"],["absenteismo","Absenteísmo por departamento"],["atestados","Declarações e atestados"],["ocorrencias","Faltas"]] as const;
export function csv(rows:any[]){if(!rows.length)return "";const keys=Object.keys(rows[0]);const esc=(v:any)=>{let s=String(v??"");if(/^[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};return [keys.join(";"),...rows.map(r=>keys.map(k=>esc(r[k])).join(";"))].join("\n")}
function download(name:string,rows:any[]){const blob=new Blob(["\ufeff"+csv(rows)],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
export function Relatorios(){
 const[competence,setCompetence]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{const{data,error}=await(supabase as any).from("time_periods").select("id,reference_year,reference_month,start_date,end_date,status,closed_at").order("end_date",{ascending:false}).limit(1);if(error)setError(error.message);setCompetence(data?.[0]??null);setLoading(false)})()},[]);
 async function exportReport(kind:string){
  setBusy(kind);setError("");const db=supabase as any;let rows:any[]=[];
  try{
   if(kind==="fechamento"){const{data,error}=await db.from("time_periods").select("reference_year,reference_month,start_date,end_date,status,closed_at").order("start_date",{ascending:false}).limit(24);if(error)throw error;rows=data??[]}
   if(kind==="banco"){const{data,error}=await db.from("bank_hours").select("entry_date,kind,minutes,previous_balance_minutes,balance_minutes,justification,employees(full_name),time_periods(reference_year,reference_month,start_date,end_date)").order("entry_date",{ascending:false});if(error)throw error;rows=(data??[]).map((x:any)=>({date:x.entry_date,competencia:x.time_periods?String(x.time_periods.reference_month).padStart(2,"0")+"/"+x.time_periods.reference_year:"",employee:x.employees?.full_name??"",kind:x.kind,minutes:x.minutes,previous_balance_minutes:x.previous_balance_minutes,balance_minutes:x.balance_minutes,justification:x.justification??""}))}
   if(kind==="extras"){const{data,error}=await db.from("overtime_records").select("reference_date,launch_type,minutes,rate_percent,estimated_value,notes,employees(full_name)").order("reference_date",{ascending:false});if(error)throw error;rows=(data??[]).map((x:any)=>({date:x.reference_date,type:x.launch_type,minutes:x.minutes,rate_percent:x.rate_percent,estimated_value:x.estimated_value,description:x.notes??"",employee:x.employees?.full_name??""}))}
   if(kind==="absenteismo"){const{data,error}=await db.from("occurrences").select("occurrence_date,end_date,quantity,unit,notes,employees(full_name,departments(name)),occurrence_types!inner(code,name)").in("occurrence_types.code",["folga_abonada","folga_descontada","falta_justificada","falta_injustificada"]);if(error)throw error;rows=(data??[]).map((x:any)=>({date:x.occurrence_date,end_date:x.end_date??"",type:x.occurrence_types?.name??"",quantity:x.quantity,unit:x.unit,employee:x.employees?.full_name??"",department:x.employees?.departments?.name??"",description:x.notes??""}))}
   if(kind==="atestados"){const[{data:certificates,error:certificateError},{data:leaves,error:leaveError}]=await Promise.all([db.from("medical_certificates").select("start_date,end_date,days,certificate_type,cid,notes,employees(full_name)").order("start_date",{ascending:false}),db.from("occurrences").select("occurrence_date,end_date,quantity,unit,notes,employees(full_name),occurrence_types!inner(code,name)").eq("occurrence_types.code","afastamento").order("occurrence_date",{ascending:false})]);if(certificateError)throw certificateError;if(leaveError)throw leaveError;rows=[...(certificates??[]).map((x:any)=>({tipo:"Atestado",employee:x.employees?.full_name??"",start_date:x.start_date,end_date:x.end_date,days:x.days,certificate_type:x.certificate_type,cid:x.cid,notes:x.notes??""})),...(leaves??[]).map((x:any)=>({tipo:"Afastamento",employee:x.employees?.full_name??"",start_date:x.occurrence_date,end_date:x.end_date??x.occurrence_date,days:x.quantity,certificate_type:"",cid:"",notes:x.notes??""}))]}
   if(kind==="ocorrencias"){const{data,error}=await db.from("occurrences").select("occurrence_date,end_date,quantity,unit,notes,employees(full_name),occurrence_types!inner(code,name)").in("occurrence_types.code",["folga_abonada","folga_descontada","falta_justificada","falta_injustificada"]);if(error)throw error;rows=(data??[]).map((x:any)=>({date:x.occurrence_date,end_date:x.end_date??"",type:x.occurrence_types?.name??"",quantity:x.quantity,unit:x.unit,employee:x.employees?.full_name??"",description:x.notes??""}))}
   download("dp-success-"+kind+".csv",rows)
  }catch(e:any){setError(e.message??"Não foi possível gerar o relatório.")}finally{setBusy("")}
 }
 return <div className="min-h-screen bg-background"><header className="border-b px-6 py-4"><div className="mx-auto flex max-w-[1500px] items-center justify-between"><a href="/" className="flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Voltar</a><span className="font-semibold">DP Success · Relatórios</span></div></header><main className="mx-auto max-w-[1500px] px-6 py-7"><p className="text-sm font-medium text-primary">Gestão</p><h1 className="mt-1 text-3xl font-bold">Relatórios</h1><p className="mt-1 text-sm text-muted-foreground">{loading?"Carregando…":competence?"Competência atual: "+String(competence.reference_month).padStart(2,"0")+"/"+competence.reference_year:"Nenhuma competência cadastrada."}</p>{error&&<div className="mt-4 rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}<div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{reports.map(([key,title])=><Card key={key} className="p-5"><FileBarChart className="h-5 w-5 text-primary"/><h2 className="mt-4 font-bold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">Exporte os dados do sistema em formato CSV.</p><button onClick={()=>void exportReport(key)} disabled={!!busy} className="mt-4 inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm disabled:opacity-50"><Download className="h-4 w-4"/>{busy===key?"Gerando…":"Exportar CSV"}</button></Card>)}</div></main></div>;
}